### ISSUE TITLE
Customize kernel?

### ISSUE THREAD

**Issue by liyimeng** [rancher/os2#12]
Is it possible to customise os kernel. I don't see it in docs/customizing.md?

I actually don't get where is the kernel come from, cos_toolkit?

**Comment by kkaempf** [comment]
Elemental's kernel comes from "SLE Micro for Rancher".
See [this Dockerfile](https://build.opensuse.org/package/view_file/isv:Rancher:Elemental:Dev:Teal53/node-image/Dockerfile?expand=1) on how we build the os image.

Not sure what you want to customize. But you could install your own kernel just as `elemental` gets installed in the above Dockerfile.
