### ISSUE TITLE
Feature Request: Allow Operator to manage being a downstream "cattle" 

### ISSUE THREAD

**Issue by Kampe** [rancher/os2#13]
Hello!

Problem:
There's seemingly no great way to manage the registration of a "edge" rancher cluster with a cloud hosted "multicluster-managment" rancher - or if there is I'm missing something fundamental about how I should be managing these "cattle" clusters I create downstream of the Rancher.

Current Solution:
We manage this ourselves by creating a k8s job that runs at runtime and utilizes a "service account" with credentials retrieved from centralized secret store to create and register the cluster with rancher "multicluster-management" which then self applies the `cattle-agent` yaml.

is there a more preferred way to manage these types of registrations with the rancher?

**Comment by kkaempf** [comment]
Please see https://rancher.github.io/elemental/ for a successor of 'os2'.
