### ISSUE TITLE
Server is not automatically reboot after installation

### ISSUE THREAD

**Issue by ldevulder** [rancher/os2#15]
I generated a RancherOS iso with `elemental-image-build` from https://github.com/rancher-sandbox/os2-opensuse-image, then installed a VM with it.
Installation went fine but there was no automatic reboot at the end, and this should be the default behaviour.

**Comment by Itxaka** [comment]
reboot on elemental seems to be correct: or at least the flag is set via the env var correctly:

```
$ ELEMENTAL_REBOOT=true bin/elemental --debug upgrade
INFO[2022-03-01T17:59:23+01:00] Elemental version version.BuildInfo{Version:"v0.0.13-2-gdd23b93", GitCommit:"dd23b9393e36fba4cb8d6f033f3888c67d9fbbd6", GoVersion:"go1.17.5"} 
DEBU[2022-03-01T17:59:23+01:00] Full config: &{RecoveryLabel:COS_RECOVERY PersistentLabel:COS_PERSISTENT StateLabel:COS_STATE OEMLabel:COS_OEM SystemLabel:COS_SYSTEM ActiveLabel:COS_ACTIVE PassiveLabel:COS_PASSIVE Target: Source: CloudInit: ForceEfi:false ForceGpt:false PartLayout: Tty: NoFormat:false Force:false Strict:false Iso: DockerImg: Cosign:false CosignPubKey: NoVerify:false CloudInitPaths: GrubDefEntry:cOs Reboot:true PowerOff:false ChannelUpgrades:false UpgradeImage: RecoveryImage: RecoveryUpgrade:false ImgSize:3072 Directory: ResetPersistent:false PartTable: BootFlag: GrubConf:/etc/cos/grub.cfg Logger:0xc0001c3260 Fs:0x1efe2b0 Mounter:0xc000536018 Runner:0x1efe2b0 Syscall:0x1efe2b0 CloudInitRunner:0xc0000200f0 Luet:<nil> Partitions:[] Images:map[] Client:0xc000020090} 
```

**Comment by Itxaka** [comment]
umm, there is no flag for reboot passed from os2 that I can see in the code...

**Comment by ldevulder** [comment]
In the code of `ros-installer` I can see a `power-off` option, but nothing related to a reboot yes (it should be the default according to `installation.md`).

**Comment by Itxaka** [comment]
@ldevulder closing it in here and tracking it on https://github.com/rancher-sandbox/os2/issues/45 instead :)
