### ISSUE TITLE
[Feature Request] Add arm64 support

### ISSUE THREAD

**Issue by TristanCottam** [rancher/os2#16]
Adding arm64 support would allow me to manage my Raspberry Pi 4B Rancher provisioning entirely through GitOps + Rancher.

**Comment by kkaempf** [comment]
We have arm64 support and are looking for testers. Would you volunteer ?

**Comment by TristanCottam** [comment]
Absolutely !

**Comment by nated0g** [comment]
I would also volunteer for this

**Comment by mazzy89** [comment]
Count on me to test this.

**Comment by mazzy89** [comment]
AFAIU the support has been added into here https://github.com/rancher-sandbox/os2. a drone build step has been in fact added but for some reasons is commented. any info about it?

**Comment by kkaempf** [comment]
Please see https://rancher.github.io/elemental/ for a successor of 'os2'.
