### ISSUE TITLE
Is there any Roadmap for RancherOS v2?

### ISSUE THREAD

**Issue by MAFLO321** [rancher/os2#2]
I'm very interested in RancherOS v2. I have also seen that the alpha release phase has already started :partying_face: .
Is there any roadmap / timeframe for this release?
When will any beta / rc / stable version be available?
When could/should RancherOS v2 be used instead of RancherOS v1?
Will there be any upgrade path from RancherOS v1 to RancherOS v2?

Thank you

ping: rancher/os#3063

**Comment by TristanCottam** [comment]
Bump, I'm myself wondering if this project will be under active development any time soon.

I understand this is still v0.1.0, but I'd love to try it out and start automating my bare-metal provisioning entirely through GitOps + Rancher !

**Comment by kkaempf** [comment]
Thanks for your interest, @happy-sadan. RancherOS2 is in development (currently happening [here](https://github.com/rancher-sandbox/os2). We don't have a roadmap at this time.

**Comment by kkaempf** [comment]
Hi @MAFLO321 !

> Is there any roadmap / timeframe for this release?

Sometime in 2022 🤞🏻 

> When will any beta / rc / stable version be available?

See last comment, development is currently happening in another repository.

> When could/should RancherOS v2 be used instead of RancherOS v1?

See above for timeframe.

> Will there be any upgrade path from RancherOS v1 to RancherOS v2?

Probably not. Want to help ? :wink:
