### ISSUE TITLE
Support container images as installation bootstrap

### ISSUE THREAD

**Issue by mudler** [rancher/os2#8]
cOS-toolkit gained the capability to bootstrap directly container images besides isos, so it should be possible to enhance the current mechanism that applies to ISOs to container images as well.

See for a reference [isoUrl](https://github.com/rancher/os2/blob/085bc09768be96ee90b07d23cbe653c485d08fc0/pkg/config/read.go#L174)

**Comment by kkaempf** [comment]
fixed in Elemental.
